apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode: proxy means Grafana proxying the request
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: IAM_DB
    type: postgres
    access: proxy
    url: db:5432
    database: ent_dash_iam
    user: postgres
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      postgresVersion: 17
