"""Init ent-dash-recon

Revision ID: aca16ad72bf6
Revises: 
Create Date: 2026-04-02 13:35:50.071276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca16ad72bf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure the rekon schema exists before creating tables inside it
    op.execute("CREATE SCHEMA IF NOT EXISTS rekon")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekon_qris_aj',
    sa.Column('id_row', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('report_datetime', sa.DateTime(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interchange_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('convenience_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('merchant_mdr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_biller', sa.Boolean(), nullable=True),
    sa.Column('is_ebiller', sa.Boolean(), nullable=True),
    sa.Column('is_cbs', sa.Boolean(), nullable=True),
    sa.Column('status_rekon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_row'),
    schema='rekon'
    )
    op.create_table('rekon_qris_onus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ref_core', sa.String(length=50), nullable=True),
    sa.Column('ref_biller', sa.String(length=50), nullable=True),
    sa.Column('merchant_pan', sa.String(length=50), nullable=True),
    sa.Column('customer_pan', sa.String(length=50), nullable=True),
    sa.Column('merchant_name', sa.String(length=100), nullable=True),
    sa.Column('merchant_location', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jenis', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('qris_switching', sa.String(length=10), nullable=True),
    sa.Column('response_code', sa.String(length=20), nullable=True),
    sa.Column('merchant_criteria', sa.String(length=50), nullable=True),
    sa.Column('status_rekon', sa.String(length=50), nullable=True),
    sa.Column('issuer_name', sa.String(length=50), nullable=True),
    sa.Column('acq_name', sa.String(length=50), nullable=True),
    sa.Column('merchant_mdr', sa.String(), nullable=True),
    sa.Column('is_biller', sa.Boolean(), nullable=True),
    sa.Column('is_echannel', sa.Boolean(), nullable=True),
    sa.Column('is_cbs', sa.Boolean(), nullable=True),
    sa.Column('porefn', sa.String(length=15), nullable=True),
    sa.Column('desc_core', sa.String(length=30), nullable=True),
    sa.Column('rekening_sumber', sa.String(length=10), nullable=True),
    sa.Column('rekening_nasabah', sa.String(length=10), nullable=True),
    sa.Column('potecn', sa.SmallInteger(), nullable=True),
    sa.Column('pobchn', sa.Integer(), nullable=True),
    sa.Column('podtpo', sa.Integer(), nullable=True),
    sa.Column('potime', sa.Integer(), nullable=True),
    sa.Column('poprog', sa.String(length=10), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('rekon_qris_rintis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ref_core', sa.String(length=50), nullable=True),
    sa.Column('ref_biller', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('merchant_pan', sa.String(length=50), nullable=True),
    sa.Column('customer_pan', sa.String(length=50), nullable=True),
    sa.Column('merchant_name', sa.String(length=100), nullable=True),
    sa.Column('merchant_location', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jenis', sa.String(length=10), nullable=True),
    sa.Column('auth_resp', sa.String(length=10), nullable=True),
    sa.Column('trace_no', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('qris_switching', sa.String(length=10), nullable=True),
    sa.Column('response_code', sa.String(length=20), nullable=True),
    sa.Column('interchange_fee', sa.String(length=50), nullable=True),
    sa.Column('convenience_fee', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('merchant_criteria', sa.String(length=50), nullable=True),
    sa.Column('trx_code', sa.String(length=50), nullable=True),
    sa.Column('status_rekon', sa.String(length=50), nullable=True),
    sa.Column('issuer_name', sa.String(length=50), nullable=True),
    sa.Column('acq_name', sa.String(length=50), nullable=True),
    sa.Column('merchant_mdr', sa.String(), nullable=True),
    sa.Column('is_biller', sa.Boolean(), nullable=True),
    sa.Column('is_echannel', sa.Boolean(), nullable=True),
    sa.Column('is_cbs', sa.Boolean(), nullable=True),
    sa.Column('porefn', sa.String(length=15), nullable=True),
    sa.Column('desc_core', sa.String(length=30), nullable=True),
    sa.Column('rekening_sumber', sa.String(length=10), nullable=True),
    sa.Column('rekening_nasabah', sa.String(length=10), nullable=True),
    sa.Column('potecn', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('pobchn', sa.Numeric(precision=5, scale=0), nullable=True),
    sa.Column('podtpo', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('potime', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('poprog', sa.String(length=10), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekon_qris_rintis', schema='rekon')
    op.drop_table('rekon_qris_onus', schema='rekon')
    op.drop_table('rekon_qris_aj', schema='rekon')
    op.execute("DROP SCHEMA IF EXISTS rekon")
    # ### end Alembic commands ###
