from sqlalchemy import Column, String, BigInteger, Numeric, DateTime, Boolean, SmallInteger, Integer, Text, Date
from app.db.base import Base

class RekonQrisAj(Base):
    __tablename__ = "rekon_qris_aj"
    __table_args__ = {"schema": "rekon"}

    id_row = Column(String, primary_key=True)
    transaction_date = Column(DateTime, nullable=True)
    report_datetime = Column(DateTime, nullable=True)
    transaction_amount = Column(Numeric(precision=15, scale=2), nullable=True)
    interchange_fee = Column(Numeric(precision=15, scale=2), nullable=True)
    convenience_fee = Column(Numeric(precision=15, scale=2), nullable=True)
    merchant_mdr = Column(Numeric(precision=8, scale=4), nullable=True)
    is_biller = Column(Boolean, default=False)
    is_ebiller = Column(Boolean, default=False)
    is_cbs = Column(Boolean, default=False)
    status_rekon = Column(String(50), nullable=True)


class RekonQrisOnus(Base):
    __tablename__ = "rekon_qris_onus"
    __table_args__ = {"schema": "rekon"}

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    ref_core = Column(String(50), nullable=True)
    ref_biller = Column(String(50), nullable=True)
    merchant_pan = Column(String(50), nullable=True)
    customer_pan = Column(String(50), nullable=True)
    merchant_name = Column(String(100), nullable=True)
    merchant_location = Column(String(100), nullable=True)
    transaction_date = Column(DateTime, nullable=True)
    transaction_amount = Column(Numeric(18, 2), nullable=True)
    description = Column(Text, nullable=True)
    jenis = Column(String(10), nullable=True)
    status = Column(String(20), nullable=True)
    qris_switching = Column(String(10), nullable=True)
    response_code = Column(String(20), nullable=True)
    merchant_criteria = Column(String(50), nullable=True)
    status_rekon = Column(String(50), nullable=True)
    issuer_name = Column(String(50), nullable=True)
    acq_name = Column(String(50), nullable=True)
    merchant_mdr = Column(String, nullable=True)
    is_biller = Column(Boolean, nullable=True)
    is_echannel = Column(Boolean, nullable=True)
    is_cbs = Column(Boolean, nullable=True)
    porefn = Column(String(15), nullable=True)
    desc_core = Column(String(30), nullable=True)
    rekening_sumber = Column(String(10), nullable=True)
    rekening_nasabah = Column(String(10), nullable=True)
    potecn = Column(SmallInteger, nullable=True)
    pobchn = Column(Integer, nullable=True)
    podtpo = Column(Integer, nullable=True)
    potime = Column(Integer, nullable=True)
    poprog = Column(String(10), nullable=True)
    bic = Column(String, nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)


class RekonQrisRintis(Base):
    __tablename__ = "rekon_qris_rintis"
    __table_args__ = {"schema": "rekon"}

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    ref_core = Column(String(50), nullable=True)
    ref_biller = Column(String(50), nullable=True)
    invoice_number = Column(String(50), nullable=True)
    merchant_pan = Column(String(50), nullable=True)
    customer_pan = Column(String(50), nullable=True)
    merchant_name = Column(String(100), nullable=True)
    merchant_location = Column(String(100), nullable=True)
    transaction_date = Column(DateTime, nullable=True)
    transaction_amount = Column(Numeric(18, 2), nullable=True)
    description = Column(Text, nullable=True)
    jenis = Column(String(10), nullable=True)
    auth_resp = Column(String(10), nullable=True)
    trace_no = Column(String(20), nullable=True)
    status = Column(String(20), nullable=True)
    qris_switching = Column(String(10), nullable=True)
    response_code = Column(String(20), nullable=True)
    interchange_fee = Column(String(50), nullable=True)
    convenience_fee = Column(String(50), nullable=True)
    institution = Column(String(100), nullable=True)
    merchant_criteria = Column(String(50), nullable=True)
    trx_code = Column(String(50), nullable=True)
    status_rekon = Column(String(50), nullable=True)
    issuer_name = Column(String(50), nullable=True)
    acq_name = Column(String(50), nullable=True)
    merchant_mdr = Column(String, nullable=True)
    is_biller = Column(Boolean, nullable=True)
    is_echannel = Column(Boolean, nullable=True)
    is_cbs = Column(Boolean, nullable=True)
    porefn = Column(String(15), nullable=True)
    desc_core = Column(String(30), nullable=True)
    rekening_sumber = Column(String(10), nullable=True)
    rekening_nasabah = Column(String(10), nullable=True)
    potecn = Column(Numeric(3, 0), nullable=True)
    pobchn = Column(Numeric(5, 0), nullable=True)
    podtpo = Column(Numeric(8, 0), nullable=True)
    potime = Column(Numeric(6, 0), nullable=True)
    poprog = Column(String(10), nullable=True)
    bic = Column(String, nullable=True)
    report_date = Column(Date, nullable=True)

