# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x06\x65ngine\"#\n\x12\x46\x61\x63tKinerjaRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\xe1\x01\n\x0e\x46\x61\x63tKinerjaRow\x12\x12\n\nketerangan\x18\x01 \x01(\t\x12\x14\n\x0cperiode_data\x18\x02 \x01(\t\x12\x10\n\x08kelompok\x18\x03 \x01(\t\x12\r\n\x05jenis\x18\x04 \x01(\t\x12\x0c\n\x04urut\x18\x05 \x01(\t\x12\x0b\n\x03wil\x18\x06 \x01(\t\x12\x10\n\x08nama_wil\x18\x07 \x01(\t\x12\x0b\n\x03\x63\x61\x62\x18\x08 \x01(\t\x12\x10\n\x08nama_cab\x18\t \x01(\t\x12\x0e\n\x06is_ajp\x18\n \x01(\x08\x12\x15\n\rtotal_nominal\x18\x0b \x01(\x01\x12\x11\n\tavg_rasio\x18\x0c \x01(\x01\"\\\n\x13\x46\x61\x63tKinerjaResponse\x12$\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x16.engine.FactKinerjaRow\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2c\n\rEngineService\x12R\n\x17GetFactKinerjaAggregate\x12\x1a.engine.FactKinerjaRequest\x1a\x1b.engine.FactKinerjaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACTKINERJAREQUEST']._serialized_start=24
  _globals['_FACTKINERJAREQUEST']._serialized_end=59
  _globals['_FACTKINERJAROW']._serialized_start=62
  _globals['_FACTKINERJAROW']._serialized_end=287
  _globals['_FACTKINERJARESPONSE']._serialized_start=289
  _globals['_FACTKINERJARESPONSE']._serialized_end=381
  _globals['_ENGINESERVICE']._serialized_start=383
  _globals['_ENGINESERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
