"""Init ent-dash-engine

Revision ID: 7f0ad24746be
Revises: 
Create Date: 2026-04-02 13:35:46.925489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0ad24746be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('minio_object_name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('target_table', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.BigInteger(), nullable=True),
    sa.Column('processed_rows', sa.BigInteger(), nullable=True),
    sa.Column('failed_rows', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('kafka_published', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('engine_job_entry_log',
    sa.Column('id_batch', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('transname', sa.String(length=255), nullable=True),
    sa.Column('stepname', sa.String(length=255), nullable=True),
    sa.Column('lines_read', sa.BigInteger(), nullable=True),
    sa.Column('lines_written', sa.BigInteger(), nullable=True),
    sa.Column('lines_updated', sa.BigInteger(), nullable=True),
    sa.Column('lines_input', sa.BigInteger(), nullable=True),
    sa.Column('lines_output', sa.BigInteger(), nullable=True),
    sa.Column('lines_rejected', sa.BigInteger(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.String(length=5), nullable=True),
    sa.Column('nr_result_rows', sa.BigInteger(), nullable=True),
    sa.Column('nr_result_files', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id_batch'),
    schema='rekon'
    )
    op.create_table('engine_job_log',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('jobname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('lines_read', sa.BigInteger(), nullable=True),
    sa.Column('lines_written', sa.BigInteger(), nullable=True),
    sa.Column('lines_updated', sa.BigInteger(), nullable=True),
    sa.Column('lines_input', sa.BigInteger(), nullable=True),
    sa.Column('lines_output', sa.BigInteger(), nullable=True),
    sa.Column('lines_rejected', sa.BigInteger(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('logdate', sa.DateTime(), nullable=True),
    sa.Column('depdate', sa.DateTime(), nullable=True),
    sa.Column('replaydate', sa.DateTime(), nullable=True),
    sa.Column('log_field', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_job'),
    schema='rekon'
    )
    op.create_table('engine_process_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_desc', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_process_group_his',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_desc', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_setting_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('connection_name', sa.String(length=50), nullable=True),
    sa.Column('connection_desc', sa.String(length=100), nullable=True),
    sa.Column('rdbms', sa.String(length=50), nullable=True),
    sa.Column('host_name', sa.String(length=50), nullable=True),
    sa.Column('database_name', sa.String(length=50), nullable=True),
    sa.Column('port_number', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_sts_load_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('process_desc', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('is_ftp_sync', sa.Boolean(), nullable=True),
    sa.Column('is_window_time', sa.Boolean(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('is_interval', sa.Boolean(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('job_location', sa.String(length=100), nullable=True),
    sa.Column('job_start_name', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=100), nullable=True),
    sa.Column('count_src', sa.BigInteger(), nullable=True),
    sa.Column('count_dest', sa.BigInteger(), nullable=True),
    sa.Column('pentaho_id_job', sa.Integer(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('log_field', sa.Text(), nullable=True),
    sa.Column('last_update_ftp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_sts_load_data_his',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('process_desc', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('is_ftp_sync', sa.Boolean(), nullable=True),
    sa.Column('is_window_time', sa.Boolean(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('is_interval', sa.Boolean(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('job_location', sa.String(length=100), nullable=True),
    sa.Column('job_start_name', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=100), nullable=True),
    sa.Column('count_src', sa.BigInteger(), nullable=True),
    sa.Column('count_dest', sa.BigInteger(), nullable=True),
    sa.Column('pentaho_id_job', sa.Integer(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('log_field', sa.Text(), nullable=True),
    sa.Column('last_update_ftp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_sts_proses_rpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('process_desc', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('is_ftp_sync', sa.Boolean(), nullable=True),
    sa.Column('is_window_time', sa.Boolean(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('is_interval', sa.Boolean(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('job_location', sa.String(length=100), nullable=True),
    sa.Column('job_start_name', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=50), nullable=True),
    sa.Column('pentaho_id_job', sa.Integer(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('log_field', sa.Text(), nullable=True),
    sa.Column('last_update_ftp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    op.create_table('engine_sts_proses_rpt_his',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('sts', sa.Boolean(), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('process_desc', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=11), nullable=True),
    sa.Column('is_ftp_sync', sa.Boolean(), nullable=True),
    sa.Column('is_window_time', sa.Boolean(), nullable=True),
    sa.Column('window_start', sa.String(length=8), nullable=True),
    sa.Column('window_end', sa.String(length=8), nullable=True),
    sa.Column('is_interval', sa.Boolean(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('job_location', sa.String(length=100), nullable=True),
    sa.Column('job_start_name', sa.String(length=100), nullable=True),
    sa.Column('status_flag', sa.String(length=1), nullable=True),
    sa.Column('status_desc', sa.String(length=50), nullable=True),
    sa.Column('pentaho_id_job', sa.Integer(), nullable=True),
    sa.Column('errors', sa.BigInteger(), nullable=True),
    sa.Column('log_field', sa.Text(), nullable=True),
    sa.Column('last_update_ftp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='rekon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engine_sts_proses_rpt_his', schema='rekon')
    op.drop_table('engine_sts_proses_rpt', schema='rekon')
    op.drop_table('engine_sts_load_data_his', schema='rekon')
    op.drop_table('engine_sts_load_data', schema='rekon')
    op.drop_table('engine_setting_db', schema='rekon')
    op.drop_table('engine_process_group_his', schema='rekon')
    op.drop_table('engine_process_group', schema='rekon')
    op.drop_table('engine_job_log', schema='rekon')
    op.drop_table('engine_job_entry_log', schema='rekon')
    op.drop_table('file_imports', schema='app')
    # ### end Alembic commands ###
