"""Init ent-dash-analytics

Revision ID: 884511b21048
Revises: 
Create Date: 2026-04-02 13:35:43.544095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884511b21048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('level', sa.BigInteger(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), nullable=True),
    sa.Column('is_link', sa.Boolean(), nullable=True),
    sa.Column('is_ratio', sa.Boolean(), nullable=True),
    sa.Column('urut', sa.BigInteger(), nullable=True),
    sa.Column('kelompok', sa.String(length=30), nullable=True),
    sa.Column('jenis', sa.String(length=1), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['app.financial_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_financial_indicators_id'), 'financial_indicators', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_financial_indicators_slug'), 'financial_indicators', ['slug'], unique=True, schema='app')
    op.create_table('financial_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('wil', sa.String(length=3), nullable=True),
    sa.Column('nama_wil', sa.String(length=30), nullable=True),
    sa.Column('cab', sa.String(length=3), nullable=True),
    sa.Column('nama_cab', sa.String(length=30), nullable=True),
    sa.Column('is_ajp', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('target_nominal', sa.Float(), nullable=True),
    sa.Column('dtd_nominal', sa.Float(), nullable=True),
    sa.Column('dtd_pct', sa.Float(), nullable=True),
    sa.Column('mtd_nominal', sa.Float(), nullable=True),
    sa.Column('mtd_pct', sa.Float(), nullable=True),
    sa.Column('ytd_nominal', sa.Float(), nullable=True),
    sa.Column('ytd_pct', sa.Float(), nullable=True),
    sa.Column('yoy_nominal', sa.Float(), nullable=True),
    sa.Column('yoy_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['app.financial_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_financial_metrics_id'), 'financial_metrics', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_financial_metrics_report_date'), 'financial_metrics', ['report_date'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_financial_metrics_report_date'), table_name='financial_metrics', schema='app')
    op.drop_index(op.f('ix_app_financial_metrics_id'), table_name='financial_metrics', schema='app')
    op.drop_table('financial_metrics', schema='app')
    op.drop_index(op.f('ix_app_financial_indicators_slug'), table_name='financial_indicators', schema='app')
    op.drop_index(op.f('ix_app_financial_indicators_id'), table_name='financial_indicators', schema='app')
    op.drop_table('financial_indicators', schema='app')
    # ### end Alembic commands ###
