"""add_missing_attributes_to_financial_models

Revision ID: 79fa1c112ca4
Revises: b067380fb666
Create Date: 2026-03-17 11:51:23.496542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fa1c112ca4'
down_revision: Union[str, None] = 'b067380fb666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_indicators', sa.Column('urut', sa.BigInteger(), nullable=True), schema='app')
    op.add_column('financial_indicators', sa.Column('kelompok', sa.String(length=30), nullable=True), schema='app')
    op.add_column('financial_indicators', sa.Column('jenis', sa.String(length=1), nullable=True), schema='app')
    op.add_column('financial_metrics', sa.Column('wil', sa.String(length=3), nullable=True), schema='app')
    op.add_column('financial_metrics', sa.Column('nama_wil', sa.String(length=30), nullable=True), schema='app')
    op.add_column('financial_metrics', sa.Column('cab', sa.String(length=3), nullable=True), schema='app')
    op.add_column('financial_metrics', sa.Column('nama_cab', sa.String(length=30), nullable=True), schema='app')
    op.add_column('financial_metrics', sa.Column('is_ajp', sa.Boolean(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_metrics', 'is_ajp', schema='app')
    op.drop_column('financial_metrics', 'nama_cab', schema='app')
    op.drop_column('financial_metrics', 'cab', schema='app')
    op.drop_column('financial_metrics', 'nama_wil', schema='app')
    op.drop_column('financial_metrics', 'wil', schema='app')
    op.drop_column('financial_indicators', 'jenis', schema='app')
    op.drop_column('financial_indicators', 'kelompok', schema='app')
    op.drop_column('financial_indicators', 'urut', schema='app')
    # ### end Alembic commands ###
