"""Initial schema setup

Revision ID: b067380fb666
Revises: 20250313_create_fact_kinerjaprc
Create Date: 2026-03-17 11:30:38.284327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b067380fb666'
down_revision: Union[str, None] = '20250313_create_fact_kinerjaprc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_indicators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('level', sa.BigInteger(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), nullable=True),
    sa.Column('is_link', sa.Boolean(), nullable=True),
    sa.Column('is_ratio', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['app.financial_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_financial_indicators_id'), 'financial_indicators', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_financial_indicators_slug'), 'financial_indicators', ['slug'], unique=True, schema='app')
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.String(length=255), nullable=True),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('causer_type', sa.String(length=255), nullable=True),
    sa.Column('causer_id', sa.BigInteger(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('batch_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('financial_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('target_nominal', sa.Float(), nullable=True),
    sa.Column('dtd_nominal', sa.Float(), nullable=True),
    sa.Column('dtd_pct', sa.Float(), nullable=True),
    sa.Column('mtd_nominal', sa.Float(), nullable=True),
    sa.Column('mtd_pct', sa.Float(), nullable=True),
    sa.Column('ytd_nominal', sa.Float(), nullable=True),
    sa.Column('ytd_pct', sa.Float(), nullable=True),
    sa.Column('yoy_nominal', sa.Float(), nullable=True),
    sa.Column('yoy_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['app.financial_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_financial_metrics_id'), 'financial_metrics', ['id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_financial_metrics_report_date'), 'financial_metrics', ['report_date'], unique=False, schema='app')
    op.drop_table('password_reset_tokens', schema='app')
    op.drop_index('model_has_permissions_model_id_model_type_index', table_name='model_has_permissions', schema='app')
    op.drop_table('model_has_permissions', schema='app')
    op.drop_index('app_personal_access_tokens_tokenable_type_tokenable_id_index', table_name='personal_access_tokens', schema='app')
    op.drop_table('personal_access_tokens', schema='app')
    op.drop_index('app_sessions_last_activity_index', table_name='sessions', schema='app')
    op.drop_index('app_sessions_user_id_index', table_name='sessions', schema='app')
    op.drop_table('sessions', schema='app')
    op.drop_table('migrations', schema='app')
    op.drop_table('postgresql_schemas', schema='app')
    op.drop_index('activity_log_log_name_index', table_name='activity_log', schema='app')
    op.drop_index('causer', table_name='activity_log', schema='app')
    op.drop_index('subject', table_name='activity_log', schema='app')
    op.drop_table('activity_log', schema='app')
    op.add_column('fact_kinerjaprc', sa.Column('id', sa.BigInteger(), nullable=False), schema='TABLEAU_REPORT')
    op.create_index(op.f('ix_TABLEAU_REPORT_fact_kinerjaprc_id'), 'fact_kinerjaprc', ['id'], unique=False, schema='TABLEAU_REPORT')
    op.alter_column('file_imports', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               schema='app')
    op.alter_column('file_imports', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Path to the final merged file in storage',
               existing_nullable=False,
               schema='app')
    op.alter_column('file_imports', 'target_table',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='E.g. rekon.rekon_qris_aj',
               existing_nullable=False,
               schema='app')
    op.alter_column('file_imports', 'total_rows',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'processed_rows',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'failed_rows',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='app')
    op.alter_column('file_imports', 'error_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='To store row-specific errors',
               existing_nullable=True,
               schema='app')
    op.drop_constraint('file_imports_user_id_foreign', 'file_imports', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'file_imports', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_index('model_has_roles_model_id_model_type_index', table_name='model_has_roles', schema='app')
    op.create_index(op.f('ix_app_organization_units_id'), 'organization_units', ['id'], unique=False, schema='app')
    op.drop_constraint('app_organization_units_parent_id_foreign', 'organization_units', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'organization_units', 'organization_units', ['parent_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_column('organization_units', 'is_active', schema='app')
    op.drop_constraint('app_permissions_name_guard_name_unique', 'permissions', schema='app', type_='unique')
    op.drop_column('permissions', 'updated_at', schema='app')
    op.drop_column('permissions', 'created_at', schema='app')
    op.alter_column('positions', 'level',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='app')
    op.alter_column('positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'),
               schema='app')
    op.drop_constraint('app_positions_name_unique', 'positions', schema='app', type_='unique')
    op.create_index(op.f('ix_app_positions_id'), 'positions', ['id'], unique=False, schema='app')
    op.drop_constraint('app_roles_name_guard_name_unique', 'roles', schema='app', type_='unique')
    op.drop_column('roles', 'updated_at', schema='app')
    op.drop_column('roles', 'created_at', schema='app')
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='app')
    op.alter_column('users', 'two_factor_recovery_codes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='app')
    op.drop_constraint('app_users_email_unique', 'users', schema='app', type_='unique')
    op.drop_constraint('app_users_employee_id_unique', 'users', schema='app', type_='unique')
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.create_index(op.f('ix_app_users_id'), 'users', ['id'], unique=False, schema='app')
    op.drop_constraint('app_users_organization_unit_id_foreign', 'users', schema='app', type_='foreignkey')
    op.drop_constraint('app_users_position_id_foreign', 'users', schema='app', type_='foreignkey')
    op.drop_constraint('app_users_direct_superior_id_foreign', 'users', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['direct_superior_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'users', 'organization_units', ['organization_unit_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_column('users', 'is_active', schema='app')
    op.drop_column('users', 'profile_photo_path', schema='app')
    op.drop_column('users', 'current_team_id', schema='app')
    op.drop_column('users', 'employee_id', schema='app')
    op.add_column('engine_job_entry_log', sa.Column('result', sa.String(length=5), nullable=True), schema='rekon')
    op.alter_column('engine_job_entry_log', 'id_batch',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               schema='rekon')
    op.drop_index('idx_engine_job_entry_log_1', table_name='engine_job_entry_log', schema='rekon')
    op.drop_index('idx_engine_job_entry_log_2', table_name='engine_job_entry_log', schema='rekon')
    op.drop_column('engine_job_entry_log', 'RESULT', schema='rekon')
    op.alter_column('engine_job_log', 'id_job',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               schema='rekon')
    op.drop_index('idx_engine_job_log_1', table_name='engine_job_log', schema='rekon')
    op.drop_index('idx_engine_job_log_2', table_name='engine_job_log', schema='rekon')
    op.drop_index('idx_engine_job_log_3', table_name='engine_job_log', schema='rekon')
    op.alter_column('engine_process_group', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'last_connection',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group', 'interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'last_connection',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'process_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_ftp_sync',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_window_time',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_interval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'job_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'job_start_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.drop_constraint('engine_sts_load_data_unique', 'engine_sts_load_data', schema='rekon', type_='unique')
    op.alter_column('engine_sts_load_data_his', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data_his', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_ftp_sync',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_window_time',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_interval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'job_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'job_start_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='rekon')
    op.drop_constraint('engine_sts_proses_rpt_unique', 'engine_sts_proses_rpt', schema='rekon', type_='unique')
    op.alter_column('engine_sts_proses_rpt_his', 'window_start',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt_his', 'window_end',
               existing_type=postgresql.TIME(precision=0),
               type_=sa.String(length=8),
               existing_nullable=True,
               schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('is_ebiller', sa.Boolean(), nullable=True), schema='rekon')
    op.alter_column('rekon_qris_aj', 'id_row',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'transaction_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'interchange_fee',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'convenience_fee',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'merchant_mdr',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'status_rekon',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='rekon')
    op.drop_index('rekon_rekon_qris_aj_ref_biller_index', table_name='rekon_qris_aj', schema='rekon')
    op.drop_index('rekon_rekon_qris_aj_ref_core_index', table_name='rekon_qris_aj', schema='rekon')
    op.drop_index('rekon_rekon_qris_aj_transaction_date_status_index', table_name='rekon_qris_aj', schema='rekon')
    op.drop_column('rekon_qris_aj', 'pobchn', schema='rekon')
    op.drop_column('rekon_qris_aj', 'podtpo', schema='rekon')
    op.drop_column('rekon_qris_aj', 'is_echannel', schema='rekon')
    op.drop_column('rekon_qris_aj', 'description', schema='rekon')
    op.drop_column('rekon_qris_aj', 'response_code', schema='rekon')
    op.drop_column('rekon_qris_aj', 'merchant_criteria', schema='rekon')
    op.drop_column('rekon_qris_aj', 'merchant_location', schema='rekon')
    op.drop_column('rekon_qris_aj', 'acq_name', schema='rekon')
    op.drop_column('rekon_qris_aj', 'merchant_pan', schema='rekon')
    op.drop_column('rekon_qris_aj', 'institution', schema='rekon')
    op.drop_column('rekon_qris_aj', 'bic', schema='rekon')
    op.drop_column('rekon_qris_aj', 'ref_core', schema='rekon')
    op.drop_column('rekon_qris_aj', 'qris_switching', schema='rekon')
    op.drop_column('rekon_qris_aj', 'jenis', schema='rekon')
    op.drop_column('rekon_qris_aj', 'customer_pan', schema='rekon')
    op.drop_column('rekon_qris_aj', 'ref_biller', schema='rekon')
    op.drop_column('rekon_qris_aj', 'potecn', schema='rekon')
    op.drop_column('rekon_qris_aj', 'status', schema='rekon')
    op.drop_column('rekon_qris_aj', 'rekening_sumber', schema='rekon')
    op.drop_column('rekon_qris_aj', 'desc_core', schema='rekon')
    op.drop_column('rekon_qris_aj', 'trx_code', schema='rekon')
    op.drop_column('rekon_qris_aj', 'issuer_name', schema='rekon')
    op.drop_column('rekon_qris_aj', 'rekening_nasabah', schema='rekon')
    op.drop_column('rekon_qris_aj', 'created_at', schema='rekon')
    op.drop_column('rekon_qris_aj', 'poprog', schema='rekon')
    op.drop_column('rekon_qris_aj', 'id', schema='rekon')
    op.drop_column('rekon_qris_aj', 'porefn', schema='rekon')
    op.drop_column('rekon_qris_aj', 'potime', schema='rekon')
    op.drop_column('rekon_qris_aj', 'merchant_name', schema='rekon')
    op.drop_column('rekon_qris_aj', 'updated_at', schema='rekon')
    op.alter_column('rekon_qris_rintis', 'porefn',
               existing_type=sa.CHAR(length=15),
               type_=sa.String(length=15),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'desc_core',
               existing_type=sa.CHAR(length=30),
               type_=sa.String(length=30),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'rekening_sumber',
               existing_type=sa.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'rekening_nasabah',
               existing_type=sa.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'poprog',
               existing_type=sa.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("''::bpchar"),
               schema='rekon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rekon_qris_rintis', 'poprog',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("''::bpchar"),
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'rekening_nasabah',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=10),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'rekening_sumber',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=10),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'desc_core',
               existing_type=sa.String(length=30),
               type_=sa.CHAR(length=30),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_rintis', 'porefn',
               existing_type=sa.String(length=15),
               type_=sa.CHAR(length=15),
               existing_nullable=True,
               schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('merchant_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('potime', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('porefn', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='ID from partner CSV file'), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('poprog', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('rekening_nasabah', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('issuer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('trx_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('desc_core', sa.TEXT(), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('rekening_sumber', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('potecn', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('ref_biller', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('customer_pan', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('jenis', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('qris_switching', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('ref_core', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('bic', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('institution', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('merchant_pan', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('acq_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('merchant_location', sa.VARCHAR(length=150), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('merchant_criteria', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('response_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('is_echannel', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('podtpo', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='rekon')
    op.add_column('rekon_qris_aj', sa.Column('pobchn', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='rekon')
    op.create_index('rekon_rekon_qris_aj_transaction_date_status_index', 'rekon_qris_aj', ['transaction_date', 'status'], unique=False, schema='rekon')
    op.create_index('rekon_rekon_qris_aj_ref_core_index', 'rekon_qris_aj', ['ref_core'], unique=False, schema='rekon')
    op.create_index('rekon_rekon_qris_aj_ref_biller_index', 'rekon_qris_aj', ['ref_biller'], unique=False, schema='rekon')
    op.alter_column('rekon_qris_aj', 'status_rekon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'merchant_mdr',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'convenience_fee',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'interchange_fee',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'transaction_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('rekon_qris_aj', 'id_row',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='rekon')
    op.drop_column('rekon_qris_aj', 'is_ebiller', schema='rekon')
    op.alter_column('engine_sts_proses_rpt_his', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt_his', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.create_unique_constraint('engine_sts_proses_rpt_unique', 'engine_sts_proses_rpt', ['job_location'], schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'job_start_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'job_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_interval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_window_time',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'is_ftp_sync',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_proses_rpt', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data_his', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data_his', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.create_unique_constraint('engine_sts_load_data_unique', 'engine_sts_load_data', ['job_location'], schema='rekon')
    op.alter_column('engine_sts_load_data', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'job_start_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'job_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_interval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               existing_nullable=True,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_window_time',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'is_ftp_sync',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'process_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_sts_load_data', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'last_connection',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group_his', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'window_end',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'window_start',
               existing_type=sa.String(length=8),
               type_=postgresql.TIME(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'last_connection',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'start_time',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'status_desc',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'status_flag',
               existing_type=sa.VARCHAR(length=1),
               nullable=False,
               schema='rekon')
    op.alter_column('engine_process_group', 'sts',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='rekon')
    op.create_index('idx_engine_job_log_3', 'engine_job_log', ['jobname', 'logdate'], unique=False, schema='rekon')
    op.create_index('idx_engine_job_log_2', 'engine_job_log', ['errors', 'status', 'jobname'], unique=False, schema='rekon')
    op.create_index('idx_engine_job_log_1', 'engine_job_log', ['id_job'], unique=False, schema='rekon')
    op.alter_column('engine_job_log', 'id_job',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               schema='rekon')
    op.add_column('engine_job_entry_log', sa.Column('RESULT', sa.VARCHAR(length=5), autoincrement=False, nullable=True), schema='rekon')
    op.create_index('idx_engine_job_entry_log_2', 'engine_job_entry_log', ['transname', 'log_date'], unique=False, schema='rekon')
    op.create_index('idx_engine_job_entry_log_1', 'engine_job_entry_log', ['id_batch'], unique=False, schema='rekon')
    op.alter_column('engine_job_entry_log', 'id_batch',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               schema='rekon')
    op.drop_column('engine_job_entry_log', 'result', schema='rekon')
    op.add_column('users', sa.Column('employee_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='app')
    op.add_column('users', sa.Column('current_team_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='app')
    op.add_column('users', sa.Column('profile_photo_path', sa.VARCHAR(length=2048), autoincrement=False, nullable=True), schema='app')
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='app')
    op.drop_constraint(None, 'users', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='app', type_='foreignkey')
    op.create_foreign_key('app_users_direct_superior_id_foreign', 'users', 'users', ['direct_superior_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.create_foreign_key('app_users_position_id_foreign', 'users', 'positions', ['position_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.create_foreign_key('app_users_organization_unit_id_foreign', 'users', 'organization_units', ['organization_unit_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.drop_index(op.f('ix_app_users_id'), table_name='users', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.create_unique_constraint('app_users_employee_id_unique', 'users', ['employee_id'], schema='app')
    op.create_unique_constraint('app_users_email_unique', 'users', ['email'], schema='app')
    op.alter_column('users', 'two_factor_recovery_codes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='app')
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='app')
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='app')
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='app')
    op.create_unique_constraint('app_roles_name_guard_name_unique', 'roles', ['name', 'guard_name'], schema='app')
    op.drop_index(op.f('ix_app_positions_id'), table_name='positions', schema='app')
    op.create_unique_constraint('app_positions_name_unique', 'positions', ['name'], schema='app')
    op.alter_column('positions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'),
               schema='app')
    op.alter_column('positions', 'level',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='app')
    op.add_column('permissions', sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='app')
    op.add_column('permissions', sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True), schema='app')
    op.create_unique_constraint('app_permissions_name_guard_name_unique', 'permissions', ['name', 'guard_name'], schema='app')
    op.add_column('organization_units', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False), schema='app')
    op.drop_constraint(None, 'organization_units', schema='app', type_='foreignkey')
    op.create_foreign_key('app_organization_units_parent_id_foreign', 'organization_units', 'organization_units', ['parent_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.drop_index(op.f('ix_app_organization_units_id'), table_name='organization_units', schema='app')
    op.create_index('model_has_roles_model_id_model_type_index', 'model_has_roles', ['model_id', 'model_type'], unique=False, schema='app')
    op.drop_constraint(None, 'file_imports', schema='app', type_='foreignkey')
    op.create_foreign_key('file_imports_user_id_foreign', 'file_imports', 'users', ['user_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    op.alter_column('file_imports', 'error_log',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='To store row-specific errors',
               existing_nullable=True,
               schema='app')
    op.alter_column('file_imports', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='app')
    op.alter_column('file_imports', 'failed_rows',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'processed_rows',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'total_rows',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'),
               schema='app')
    op.alter_column('file_imports', 'target_table',
               existing_type=sa.VARCHAR(length=255),
               comment='E.g. rekon.rekon_qris_aj',
               existing_nullable=False,
               schema='app')
    op.alter_column('file_imports', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               comment='Path to the final merged file in storage',
               existing_nullable=False,
               schema='app')
    op.alter_column('file_imports', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='app')
    op.drop_index(op.f('ix_TABLEAU_REPORT_fact_kinerjaprc_id'), table_name='fact_kinerjaprc', schema='TABLEAU_REPORT')
    op.drop_column('fact_kinerjaprc', 'id', schema='TABLEAU_REPORT')
    op.create_table('activity_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('log_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('causer_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('causer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('batch_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='activity_log_pkey'),
    schema='app'
    )
    op.create_index('subject', 'activity_log', ['subject_type', 'subject_id'], unique=False, schema='app')
    op.create_index('causer', 'activity_log', ['causer_type', 'causer_id'], unique=False, schema='app')
    op.create_index('activity_log_log_name_index', 'activity_log', ['log_name'], unique=False, schema='app')
    op.create_table('postgresql_schemas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='postgresql_schemas_pkey'),
    schema='app'
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migrations_pkey'),
    schema='app'
    )
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_activity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    schema='app'
    )
    op.create_index('app_sessions_user_id_index', 'sessions', ['user_id'], unique=False, schema='app')
    op.create_index('app_sessions_last_activity_index', 'sessions', ['last_activity'], unique=False, schema='app')
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tokenable_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('abilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='personal_access_tokens_pkey'),
    sa.UniqueConstraint('token', name='app_personal_access_tokens_token_unique'),
    schema='app'
    )
    op.create_index('app_personal_access_tokens_tokenable_type_tokenable_id_index', 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False, schema='app')
    op.create_table('model_has_permissions',
    sa.Column('permission_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['app.permissions.id'], name='app_model_has_permissions_permission_id_foreign', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'model_id', 'model_type', name='model_has_permissions_pkey'),
    schema='app'
    )
    op.create_index('model_has_permissions_model_id_model_type_index', 'model_has_permissions', ['model_id', 'model_type'], unique=False, schema='app')
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='password_reset_tokens_pkey'),
    schema='app'
    )
    op.drop_index(op.f('ix_app_financial_metrics_report_date'), table_name='financial_metrics', schema='app')
    op.drop_index(op.f('ix_app_financial_metrics_id'), table_name='financial_metrics', schema='app')
    op.drop_table('financial_metrics', schema='app')
    op.drop_table('activity_log', schema='public')
    op.drop_index(op.f('ix_app_financial_indicators_slug'), table_name='financial_indicators', schema='app')
    op.drop_index(op.f('ix_app_financial_indicators_id'), table_name='financial_indicators', schema='app')
    op.drop_table('financial_indicators', schema='app')
    # ### end Alembic commands ###
